---
title: "Title"
author: "Author"
date: "Date"
header-includes:
   - \usepackage{bbm, amsmath,amsfonts,amsthm,amssymb,mathrsfs,amsxtra,amscd,latexsym, xcolor, graphicx}
output: pdf_document
---

```{r setup, include=FALSE}
#the include=FALSE in this chunk means the chunk will not appear in the knitted PDF. 
#for most of your code, you probably do want it to appear in your final report, and so don't type include=FALSE
#in order to run this code, you will need to install these packages. You can do so by going to the install button, or by going to the console and typing, for example, install.packages("knitr")
library(knitr)
library(latex2exp)
library(Lahman)
library(glmnet)
library(tidyverse)
library(devtools)
player_data = read.csv("nba_players_stats/player_data.csv")
players = read.csv("nba_players_stats/Players.csv")
seasons_stats = read.csv("nba_players_stats/Seasons_Stats.csv")
```

```{r}
#First, we filter our players data to those that started after 1985 and ended thier careers before 2020
new_players = filter(player_data, year_start >= 1985, year_end <= 2020)
new_players$Player = new_players$name
new_players
```


```{r}
#merge in with seasonal stats data to get more data points
stats = filter(seasons_stats, Year >= 1985)
merged_data = merge(new_players, stats, by = c('Player'))
```


```{r}
#create additional column for years in league
merged_data$years_in_league = merged_data$Year - merged_data$year_start
cols = colnames(merged_data)
cols
```
```{r}
#pick out stats we need, constructing complete data frame.
complete_data = merged_data[, c(2, 3, 4, 11, 13, 62, 18, 56, 57, 58, 59, 60, 61)]
complete_data = filter(complete_data, years_in_league >= 0, year_end >= Year)
complete_data
```

```{r}
#plot how PER changes with years in the league 
ggplot(complete_data, aes(years_in_league, PER)) + geom_point() 

```

```{r}
#create a "prime PER" stat, which is one std above the avg per across whole career
sample_players = filter(new_players, year_start >= 1990, year_end <= 2015)
sample_players

prime_per = c()
name = c()

for (x in 1:1399) {
  current_player = sample_players$name[x]
  current_dat = filter(complete_data, name == current_player)
  prime_per = append(prime_per, mean(current_dat$PER) + sd(current_dat$PER))
  name = append(name, current_player)
  
}

new_df = data.frame(name, prime_per)
new_df = na.omit(new_df)
new_df

```

```{r}
with_prime = merge(complete_data, new_df, by = c('name'))
with_prime = na.omit(with_prime)
with_prime$is_prime = with_prime$PER >= with_prime$prime_per
with_prime

ggplot(with_prime, aes(years_in_league, PER, color= is_prime)) + geom_point(alpha = 0.5) 

```

```{r}

# as such, it would be useful to see which stats actually have an impact on PER so verify that aging has an impact

#running ridge regression
linear.model = lm(PER~.-name, data = with_prime)
mat = model.matrix(linear.model)[,-1]
ridge_reg = glmnet(mat, with_prime$PER, alpha=0, family="gaussian")
ridge_reg_err = cv.glmnet(mat, with_prime$PER, alpha=0, family="gaussian")
plot(ridge_reg_err) 

beta_CV= coef(ridge_reg, alpha=0,
  s=ridge_reg_err$lambda.min,
  exact=TRUE,
  x = mat,
  y = y)
beta_CV #coefficient vector

#we see that age is not actually a strong predictor of PER
```


```{r}
histogram_dat = with_prime[,c(6, 14, 15)]
counts = c()
histogram_dat

for (x in 1:8574) {
  if (histogram_dat$is_prime[x] == TRUE & histogram_dat$prime_per[x] >= 20) {
    counts = append(counts, histogram_dat$years_in_league[x])
  }
}
hist(counts, xlab = "years in the league", breaks = 12)
counts
```



```{r}
years_and_per = complete_data[,c(6, 7)]
years_and_per = na.omit(years_and_per)

per_avg = c()
year_number = c()

for (x in 1:22) {
  pers = filter(years_and_per, years_in_league == x)
  year_number = append(year_number, x)
  pers
  per_avg = append(per_avg, mean(pers$PER))
  
}

per_avg[21] = 0


years_and_per_avg = data.frame(year_number, per_avg)
years_and_per_avg

```

```{r}
ggplot(data=years_and_per_avg, aes(year_number, per_avg)) + geom_line() + labs(x="Years in League", y = "Average PER")
```


```{r}
lebron = filter(seasons_stats, Player == 'LeBron James')
plot(lebron$Year, lebron$PER)
abline(h = mean(lebron$PER))

kobe = filter(seasons_stats, Player == 'Kobe Bryant')
plot(kobe$Year, kobe$PER)
abline(h = mean(kobe$PER))

dwight = filter(seasons_stats, Player == 'Dwight Howard')
plot(dwight$Year, dwight$PER)
abline(h = mean(dwight$PER))

td = filter(seasons_stats, Player == 'Tim Duncan')
plot(td$Year, td$PER)
abline(h = mean(td$PER))

mj = filter(seasons_stats, Player == 'Michael Jordan*')
plot(mj$Year, mj$PER)
abline(h = mean(mj$PER))
```


```{r}
# TODO:
# flatten the data, we want every players career to be one column. insead of per year PER have PER yr1, PER yr2, PER yr2, and box data (age entering league, blocks, etc.)
player_names = unique(with_prime[c("name")])
per_yr1 = c()
per_yr2 = c()
prediction_df <- data.frame(matrix(ncol = 15, nrow = 0))
colnames(prediction_df) <-c("name", "per_yr1", "per_yr2","per_yr3","per_yr4","per_yr5","per_yr6", "per_yr7","pts_yr1", "pts_yr2", "pts_yr3", "pts_yr4", "pts_yr5", "pts_yr6", "pts_yr7")
for (x in 2:1054){
  player_df = filter(with_prime, name == player_names[x,1]) 
  if (dim(player_df)[1] > 7){
    player_df = player_df[order(player_df$Year),]
    new_row = c(player_df[1,1],player_df[1,7],player_df[2,7],player_df[3,7],player_df[4,7],player_df[5,7], 
                player_df[6,7], player_df[7,7], player_df[1,13], player_df[2,13], player_df[3,13], player_df[4,13], 
                player_df[5,13], player_df[6,13], player_df[7,13])
    prediction_df[nrow(prediction_df) + 1,] <- new_row
  }
}
print(prediction_df)
```

```{r}
prediction_df = merge(prediction_df, sample_players, by = c('name'))
prediction_df = prediction_df[,c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20)]
prediction_df = na.omit(prediction_df)

print(prediction_df)
# need to then create a function that will take a column and will run k-nn (20ish?) on the complete data.
#from there we will have the nearest neighbors for a given player. for each of those players, each into the complete data and see what their trajectory looks like for thier careers. etc. graph the avg of the neighbors PER over thier first 5 years in the league.
# from there, ALSO report how accurate our prediction was compared to the players first 5 years if available)
```


```{r}
find.neighbors= function (player){
  #find the 10 closest nieghbors using first 2 yr PER/PTS and box data
  player_col = filter(prediction_df, prediction_df$name == player)
  print(player_col)
  neighbors <- data.frame(matrix(ncol = 9, nrow = 0))
  colnames(neighbors) <-c("name", "distance","per_yr1", "per_yr2","per_yr3","per_yr4","per_yr5","per_yr6", "per_yr7")
  for (x in 1:497) {
    other_player = prediction_df[x,]
      if (other_player$name != player_col$name){
            distance = (as.double(other_player$per_yr1) - as.double(player_col$per_yr1))**2 + (other_player$weight - player_col$weight)**2 + (as.double(other_player$per_yr2) - as.double(player_col$per_yr2))**2 + (as.double(other_player$pts_yr2) - as.double(player_col$pts_yr2))**2 + (as.double(other_player$pts_yr1) - as.double(player_col$pts_yr1))**2 
      new_row <- c(other_player$name, distance, other_player$per_yr1, other_player$per_yr2,other_player$per_yr3, other_player$per_yr4,other_player$per_yr5,other_player$per_yr6, other_player$per_yr7)
      
      if (dim(neighbors)[1] < 10){
        neighbors[nrow(neighbors) + 1,] <- new_row
      } 
      else {
        max = max(neighbors$distance)
        if (max > distance){
          neighbors = filter(neighbors, distance != max)
          neighbors[nrow(neighbors) + 1,] <- new_row
        }
      }
    }
  }
  print(neighbors)
  #create df of the avg of the neighbors career stats
  predictions = data.frame(matrix(ncol = 3, nrow = 0))
  colnames(predictions) <-c("yr", "per", "is_pred")
  predicted_per1 = c(1,mean(as.double(neighbors$per_yr1)), TRUE)
  predictions[nrow(predictions) + 1,] <- predicted_per1
  predicted_per2 = c(2,mean(as.double(neighbors$per_yr2)), TRUE)
  predictions[nrow(predictions) + 1,] <- predicted_per2
  predicted_per3 = c(3,mean(as.double(neighbors$per_yr3)), TRUE)
  predictions[nrow(predictions) + 1,] <- predicted_per3
  predicted_per4 = c(4,mean(as.double(neighbors$per_yr4)), TRUE)
  predictions[nrow(predictions) + 1,] <- predicted_per4
  predicted_per5 = c(5,mean(as.double(neighbors$per_yr5)), TRUE)
  predictions[nrow(predictions) + 1,] <- predicted_per5
  predicted_per6 = c(6,mean(as.double(neighbors$per_yr6)), TRUE)
  predictions[nrow(predictions) + 1,] <- predicted_per6
  predicted_per7 = c(7,mean(as.double(neighbors$per_yr7)), TRUE)
  predictions[nrow(predictions) + 1,] <- predicted_per7
  
  #real data
  per1 = c(1,player_col$per_yr1, FALSE)
  predictions[nrow(predictions) + 1,] <- per1
  per2 = c(2,player_col$per_yr2, FALSE)
  predictions[nrow(predictions) + 1,] <- per2
  per3 = c(3,player_col$per_yr3, FALSE)
  predictions[nrow(predictions) + 1,] <- per3
  per4 = c(4,player_col$per_yr4, FALSE)
  predictions[nrow(predictions) + 1,] <- per4
  per5 = c(5,player_col$per_yr5, FALSE)
  predictions[nrow(predictions) + 1,] <- per5
  per6 = c(6,player_col$per_yr6, FALSE)
  predictions[nrow(predictions) + 1,] <- per6
  per7 = c(7,player_col$per_yr7, FALSE)
  predictions[nrow(predictions) + 1,] <- per7
  ggplot(data = predictions, aes(yr, per, color=is_pred)) + geom_point()
  #graph the real data
  
  #find MSE
}

find.neighbors("Jamario Moon")
```


